name: Build and Publish an Image to Dockerhub
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-env name=DOCKER_REPOSITORY::${GITHUB_REPOSITORY##*/}"
      - uses: docker/build-push-action@e5e36c4a4e2085c523c6fb6a553b8d00c30c1716
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_ORG }}/${{ env.DOCKER_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
